#!/bin/bash

# Define the directory you want to clean up
target_dir="/path/to/target_directory"

# Define the list of files you want to keep (separated by spaces)
files_to_keep="file1.txt file2.txt file3.txt"

# Use find to identify files to remove
find "$target_dir" -type f ! -name "$files_to_keep" -exec rm {} \;
